name: omnitry
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - python=3.12.9=h5148396_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py312h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.7.0
      - aiofiles==23.2.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.1
      - diffusers==0.33.1
      - einops==0.8.1
      - fastapi==0.115.12
      - ffmpy==0.5.0
      - filelock==3.18.0
      - fsspec==2025.5.1
      - gradio==5.6.0
      - gradio-client==1.4.3
      - h11==0.16.0
      - hf-xet==1.1.2
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.32.1
      - idna==3.10
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - orjson==3.10.18
      - packaging==25.0
      - pandas==2.2.3
      - peft==0.13.2
      - pillow==11.2.1
      - protobuf==3.20.3
      - psutil==7.0.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pygments==2.19.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.12
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - ruff==0.11.11
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.14.0
      - tokenizers==0.20.3
      - tomlkit==0.12.0
      - torch==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.45.0
      - triton==3.3.0
      - typer==0.16.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - websockets==12.0
      - zipp==3.22.0
prefix: /home/fengyutong/anaconda3/envs/omnitry
